
version: '3'


services:

  webapp-dev:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: pydo-dev:dev
    container_name: pydo-dev
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    # not needed unless opened as a service
    # ports:
    #  - "4000:4000"
    volumes:
     - ./app:/app
    # not needed unless opened as a service
    # environment:
    # # flask vars
    #  - FLASK_HOST=0.0.0.0
    #  - FLASK_PORT=80
    #  - FLASK_APP=main.py
    #  - FLASK_DEBUG=1
    # command: /usr/bin/supervisord

  mysql:
    image: mysql:5.7
    container_name: pydo-mysql-dev
    restart: always
    volumes:
     - ./mysql_store_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pydo

  adminer:
    image: adminer:4.6.2
    container_name: pydo-adminer-dev
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0.9-alpine
    container_name: pydo-redis-dev
    restart: always
    volumes:
     - ./redis_store_dev:/data

